### PR TITLE
Storefront 2.3 compatibility

### PR DESCRIPTION
**Pull request by tiagonoronha**
### What to test

* Breadcrumb
* Font Awesome
* Secondary navigation + Site branding

### What to look for

**Breadcrumb**

The breacrumb is in the correct location (compare against the demo site)

**Font Awesome**

All Font Awesome icons are correctly displayed, no empty icons.

**Secondary navigation + Site branding**

Secondary navigation is displayed in the correct location and site branding section has the correct size (compare against the demo)

Test with and without the secondary navigation and/or with and without  WooCommerce activated.

### CODE REVIEW

**Comment by yatgirl** [comment]
Breadcrumb - demo site - it looks like a huge amount of wasted white space above and below the breadcrumb - does the breadcrumb really need to have that much space above and below it ?  Hope there is a way to adjust it.....

**Comment by tiagonoronha** [comment]
@yatgirl Thanks for your feedback. At this time we are not looking into changing the design for this theme.

Let me know if you need help tweaking the space above/bellow the breadcrumb. :)

**Comment by yatgirl** [comment]
If you have a css or code snippet I could use, then that would be very helpful - thanks !

**Comment by tiagonoronha** [comment]
@yatgirl 

`.woocommerce-breadcrumb {
     margin: -2.618em 0 2.618em;
     padding: 0 0 1em;
}`

**Pull request merged**
